#!/usr/bin/env bash

# Get latest version in Storage
LATEST_VERSION=$(gsutil ls gs://soccer_models/|   tail -1  | grep -Eo '[0-9]')

# Write to a file so we read it
echo $LATEST_VERSION > /home/marcoyel21/airflow/dags/soccerguru/predict/latest_version.txt
