#!/usr/bin/env bash

# Create the new distribution
# python /home/airflow/dags/dags-model/setup.py sdist

# Get latest version in Storage
LATEST_VERSION=$(gsutil ls gs://ubiquitous-goggles-bucket/football-prediction/ | awk '{ print substr( $0, 53) }' | sed 's/.$//' | sed 1,1d | sort -n | tail -1)
NEW_LATEST_VERSION=$((LATEST_VERSION+1))

# Upload files to the new latest version folder in Storage
sudo gsutil cp /home/airflow/dags/dags-model/model.pkl gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/
sudo gsutil cp /home/airflow/dags/dags-model/processor_state.pkl gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/
sudo gsutil cp /home/airflow/dags/dags-model/preprocess.py gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/
sudo gsutil cp /home/airflow/dags/dags-model/model_prediction.py gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/
sudo gsutil cp /home/airflow/dags/dags-model/dist/football_predict-0.1.tar.gz gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/packages/football_predict-0.1.tar.gz

# Configurate ai-platform
sudo gcloud config set ai_platform/region global

# Upload the new version of the model (thi stakes some time)
sudo gcloud beta ai-platform versions create v$NEW_LATEST_VERSION --model football_match_predictions --python-version 3.7 --runtime-version 2.8 --origin gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/ --package-uris gs://ubiquitous-goggles-bucket/football-prediction/v$NEW_LATEST_VERSION/packages/football_predict-0.1.tar.gz --prediction-class model_prediction.CustomModelPrediction